name: docker
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build container
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: ghcr.io/${GITHUB_ACTOR}/${GITHUB_REPOSITORY}:$(echo $GITHUB_SHA | head -c7)

    - name: Push Container
      uses: docker/build-push-action@v5
      with:
        push: push
        tags:
          - ghcr.io/${GITHUB_ACTOR}/${GITHUB_REPOSITORY}:$(echo $GITHUB_SHA | head -c7)
          - ghcr.io/${GITHUB_ACTOR}/${GITHUB_REPOSITORY}:latest

